### ISSUE TITLE
Please document how to run the vault copy script

### ISSUE THREAD

**Issue by brian-leveille** [clone2020/ShellScripts#1]
Please create a README documenting how to use the vault_cp script.

What is the use-case of this script (what does it do?)?
What are the requirements on the command line?
What are the requirements for vault sessions?
Are any ENV VARs supported?
Is there a dry-run flag?
What does successful output look like?  Failed?

**Comment by clone2020** [comment]
https://github.com/clone2020/ShellScripts/blob/main/README.md

To copy secrets in Hashicorp vault from one project to other use the below script.
https://github.com/clone2020/ShellScripts/blob/main/vault_cp.bash

For using the script, please create the empty porject in vault and then provide the required values similar to as shown below.

$vault login

$./vault_cp.bash <original_project>/ <destination_project>/
